const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.JavaScriptInEvents.共用_Event2,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.登入_Event8_Act1,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.JavaScriptInEvents.顯示房_Event7_Act1,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.JavaScriptInEvents.顯示房_Event10_Act1,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len
	];
};
self.C3_JsPropNameTable = [
	{JSON: 0},
	{文本: 0},
	{觸控: 0},
	{精靈2: 0},
	{時間: 0},
	{精靈: 0},
	{黑板按鈕: 0},
	{編號: 0},
	{精靈5: 0},
	{顯示: 0},
	{精靈3: 0},
	{狀態顯示2: 0},
	{stage: 0},
	{sofartime: 0},
	{flag: 0},
	{playerNB: 0},
	{nowtime: 0},
	{flaganswer: 0},
	{MyFlag: 0},
	{StartTime: 0},
	{Value: 0},
	{finalanswer: 0},
	{輸入答案: 0}
];

self.InstanceType = {
	JSON: class extends self.IJSONInstance {},
	文本: class extends self.ITextInstance {},
	觸控: class extends self.IInstance {},
	精靈2: class extends self.ISpriteInstance {},
	時間: class extends self.ITextInstance {},
	精靈: class extends self.ISpriteInstance {},
	黑板按鈕: class extends self.ISpriteInstance {},
	精靈5: class extends self.ISpriteInstance {},
	顯示: class extends self.ISpriteInstance {},
	精靈3: class extends self.ISpriteInstance {},
	狀態顯示2: class extends self.ITextInstance {}
}